#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_AT_PROTOCOL_MAX_LINE_LENGTH 128U
#define APP_UART_TUNNEL_MAX_PAYLOAD_SIZE 32U
#define APP_UART_RX_CHUNK_SIZE 64U
#define APP_UART_RING_BUFFER_SIZE 256U
#define APP_UART_TX_TIMEOUT_MS 100U
#define APP_PWM_MAX_PERCENT 100U

#endif
